### ISSUE TITLE
How to download files to Download directory?

### ISSUE THREAD

**Issue by d-apps** [nplaceit/downloads_path_provider#1]
I'm trying to download videos to download files to Download folder but because of " **'** " I can't save anything.

```
Directory dir = await DownloadsPathProvider.downloadsDirectory;

        path = "$dir/${tricks[0]}.mp4";

        print(path);
```

'/storage/emulated/0/Download'/ATW - Around the World.mp4

**Comment by daniel-mf** [comment]
`DownloadsPathProvider.downloadsDirectory` is returning quoted string?

That's really strange.
I might be checking this out by the weekend.

You could use this workaround for now: 
```dart
dir = dir.replaceAll("'", '');
```

**Comment by duzenko** [comment]
The path returned on iOS - is it even writable at all on iPhones? I know it is in simulator but that's useless.
If it is not writable, then what is the meaning of this plugin? I think it should be taken down.

**Comment by daniel-mf** [comment]
This plugin was previously only supported on Android, I haven't tested the
iOS supporting changes. I might be taking it down anyways.

**Comment by anisalibegic** [comment]
> This plugin was previously only supported on Android, I haven't tested the iOS supporting changes. I might be taking it down anyways.

Please add a note that this only works on Android. I tested on iOS and it's returning a path that does not exist at all.
